import { ThemedStyledFunction } from 'styled-components';

// Corrige o problema com styled-components
declare module 'styled-components' {
  // Add missing exports
  export function createGlobalStyle(first: TemplateStringsArray, ...rest: any[]): any;
  export const ThemeProvider: any;
  export type ThemeProviderComponent<T extends object> = any;
  
  export interface StyledComponent<C extends keyof JSX.IntrinsicElements | React.ComponentType<any>, T extends object, O extends object = {}, A extends keyof any = never> extends React.ForwardRefExoticComponent<any> {}
  
  export const styled: {
    [key: string]: ThemedStyledFunction<any, any>;
    
    a: ThemedStyledFunction<'a', any>;
    abbr: ThemedStyledFunction<'abbr', any>;
    address: ThemedStyledFunction<'address', any>;
    area: ThemedStyledFunction<'area', any>;
    article: ThemedStyledFunction<'article', any>;
    aside: ThemedStyledFunction<'aside', any>;
    audio: ThemedStyledFunction<'audio', any>;
    b: ThemedStyledFunction<'b', any>;
    base: ThemedStyledFunction<'base', any>;
    bdi: ThemedStyledFunction<'bdi', any>;
    bdo: ThemedStyledFunction<'bdo', any>;
    big: ThemedStyledFunction<'big', any>;
    blockquote: ThemedStyledFunction<'blockquote', any>;
    body: ThemedStyledFunction<'body', any>;
    br: ThemedStyledFunction<'br', any>;
    button: ThemedStyledFunction<'button', any>;
    canvas: ThemedStyledFunction<'canvas', any>;
    caption: ThemedStyledFunction<'caption', any>;
    cite: ThemedStyledFunction<'cite', any>;
    code: ThemedStyledFunction<'code', any>;
    col: ThemedStyledFunction<'col', any>;
    colgroup: ThemedStyledFunction<'colgroup', any>;
    data: ThemedStyledFunction<'data', any>;
    datalist: ThemedStyledFunction<'datalist', any>;
    dd: ThemedStyledFunction<'dd', any>;
    del: ThemedStyledFunction<'del', any>;
    details: ThemedStyledFunction<'details', any>;
    dfn: ThemedStyledFunction<'dfn', any>;
    dialog: ThemedStyledFunction<'dialog', any>;
    div: ThemedStyledFunction<'div', any>;
    dl: ThemedStyledFunction<'dl', any>;
    dt: ThemedStyledFunction<'dt', any>;
    em: ThemedStyledFunction<'em', any>;
    embed: ThemedStyledFunction<'embed', any>;
    fieldset: ThemedStyledFunction<'fieldset', any>;
    figcaption: ThemedStyledFunction<'figcaption', any>;
    figure: ThemedStyledFunction<'figure', any>;
    footer: ThemedStyledFunction<'footer', any>;
    form: ThemedStyledFunction<'form', any>;
    h1: ThemedStyledFunction<'h1', any>;
    h2: ThemedStyledFunction<'h2', any>;
    h3: ThemedStyledFunction<'h3', any>;
    h4: ThemedStyledFunction<'h4', any>;
    h5: ThemedStyledFunction<'h5', any>;
    h6: ThemedStyledFunction<'h6', any>;
    head: ThemedStyledFunction<'head', any>;
    header: ThemedStyledFunction<'header', any>;
    hgroup: ThemedStyledFunction<'hgroup', any>;
    hr: ThemedStyledFunction<'hr', any>;
    html: ThemedStyledFunction<'html', any>;
    i: ThemedStyledFunction<'i', any>;
    iframe: ThemedStyledFunction<'iframe', any>;
    img: ThemedStyledFunction<'img', any>;
    input: ThemedStyledFunction<'input', any>;
    ins: ThemedStyledFunction<'ins', any>;
    kbd: ThemedStyledFunction<'kbd', any>;
    keygen: ThemedStyledFunction<'keygen', any>;
    label: ThemedStyledFunction<'label', any>;
    legend: ThemedStyledFunction<'legend', any>;
    li: ThemedStyledFunction<'li', any>;
    link: ThemedStyledFunction<'link', any>;
    main: ThemedStyledFunction<'main', any>;
    map: ThemedStyledFunction<'map', any>;
    mark: ThemedStyledFunction<'mark', any>;
    marquee: ThemedStyledFunction<'marquee', any>;
    menu: ThemedStyledFunction<'menu', any>;
    menuitem: ThemedStyledFunction<'menuitem', any>;
    meta: ThemedStyledFunction<'meta', any>;
    meter: ThemedStyledFunction<'meter', any>;
    nav: ThemedStyledFunction<'nav', any>;
    noscript: ThemedStyledFunction<'noscript', any>;
    object: ThemedStyledFunction<'object', any>;
    ol: ThemedStyledFunction<'ol', any>;
    optgroup: ThemedStyledFunction<'optgroup', any>;
    option: ThemedStyledFunction<'option', any>;
    output: ThemedStyledFunction<'output', any>;
    p: ThemedStyledFunction<'p', any>;
    param: ThemedStyledFunction<'param', any>;
    picture: ThemedStyledFunction<'picture', any>;
    pre: ThemedStyledFunction<'pre', any>;
    progress: ThemedStyledFunction<'progress', any>;
    q: ThemedStyledFunction<'q', any>;
    rp: ThemedStyledFunction<'rp', any>;
    rt: ThemedStyledFunction<'rt', any>;
    ruby: ThemedStyledFunction<'ruby', any>;
    s: ThemedStyledFunction<'s', any>;
    samp: ThemedStyledFunction<'samp', any>;
    script: ThemedStyledFunction<'script', any>;
    section: ThemedStyledFunction<'section', any>;
    select: ThemedStyledFunction<'select', any>;
    small: ThemedStyledFunction<'small', any>;
    source: ThemedStyledFunction<'source', any>;
    span: ThemedStyledFunction<'span', any>;
    strong: ThemedStyledFunction<'strong', any>;
    style: ThemedStyledFunction<'style', any>;
    sub: ThemedStyledFunction<'sub', any>;
    summary: ThemedStyledFunction<'summary', any>;
    sup: ThemedStyledFunction<'sup', any>;
    table: ThemedStyledFunction<'table', any>;
    tbody: ThemedStyledFunction<'tbody', any>;
    td: ThemedStyledFunction<'td', any>;
    textarea: ThemedStyledFunction<'textarea', any>;
    tfoot: ThemedStyledFunction<'tfoot', any>;
    th: ThemedStyledFunction<'th', any>;
    thead: ThemedStyledFunction<'thead', any>;
    time: ThemedStyledFunction<'time', any>;
    title: ThemedStyledFunction<'title', any>;
    tr: ThemedStyledFunction<'tr', any>;
    track: ThemedStyledFunction<'track', any>;
    u: ThemedStyledFunction<'u', any>;
    ul: ThemedStyledFunction<'ul', any>;
    var: ThemedStyledFunction<'var', any>;
    video: ThemedStyledFunction<'video', any>;
    wbr: ThemedStyledFunction<'wbr', any>;
  };
} 